# Generated by Django 5.2.7 on 2025-11-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_league_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.CreateModel(
            name='PlayerInLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
            options={
                'unique_together': {('player', 'league')},
            },
        ),
        migrations.CreateModel(
            name='TeamInLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
            options={
                'unique_together': {('team', 'league')},
            },
        ),
    ]
